apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres#2025@"
            - name: POSTGRES_DB
              value: "SalesApi"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata/data"   # Subdiretório adicionado aqui
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data/pgdata
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
